# Generated by Django 5.2.6 on 2025-09-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_appraisalcycle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmaster',
            name='appraisal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisalcycle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appraisalcycle',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratingmaster',
            name='appraisal_cycle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ratingmaster',
            name='rating_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weightagemaster',
            name='appraisal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
