# Generated by Django 5.2.6 on 2025-09-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_city_country_alter_department_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('appraisal_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.appraisalcycle')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='masters.employee')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.role')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_appraisals', to='masters.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalKPIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('supervisor_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('appraisal_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_responses', to='masters.appraisalform')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.kpi')),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.kra')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=255)),
                ('weightage', models.PositiveIntegerField()),
                ('appraisal_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='masters.appraisalform')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('achieved', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='masters.employeeobjective')),
            ],
        ),
    ]
