# Generated by Django 5.2.6 on 2025-09-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_appraisalform_appraisalkpiresponse_employeeobjective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeobjective',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='masters.employee'),
        ),
    ]
