# Generated by Django 5.2.6 on 2025-09-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_employeeobjective_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='kra',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmployeeKRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by_manager', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.employee')),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.kra')),
            ],
            options={
                'unique_together': {('employee', 'kra')},
            },
        ),
    ]
