# Generated by Django 5.2.6 on 2025-09-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeekra',
            name='appraisal_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.appraisalform'),
        ),
    ]
