# Generated by Django 5.2.6 on 2025-09-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_employeekra_appraisal_form'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeekra',
            unique_together={('employee', 'kra', 'appraisal_form')},
        ),
    ]
