# Generated by Django 5.2.6 on 2025-11-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_alter_employeekra_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree_course', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.FileField(blank=True, help_text='Upload certificate, transcript, or letter of completion', null=True, upload_to='education_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='masters.employee')),
            ],
            options={
                'ordering': ['-to_date', '-from_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('Parent', 'Parent'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='masters.employee')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('contact_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('highest_education', models.CharField(blank=True, choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', "Bachelor's Degree"), ('Master', "Master's Degree"), ('Doctorate', 'Doctorate')], max_length=100, null=True)),
                ('working_rights', models.CharField(blank=True, help_text='HR Admin Only - e.g., Citizen, Work Visa, etc.', max_length=255, null=True)),
                ('allergies', models.TextField(blank=True, help_text='Any medical allergies', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='masters.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('Resume', 'Resume'), ('Application Form', 'Application Form'), ('Aptitude Test', 'Aptitude Test'), ('Interview Guide', 'Interview Guide'), ('Presentation', 'Presentation'), ('Training Checklist', 'Training Checklist'), ('Other', 'Other')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='personnel_documents/%Y/%m/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_documents', to='masters.employee')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
