# Generated by Django 5.2.6 on 2025-11-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_education_emergencycontact_employeepersonaldetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
