# Generated by Django 5.2.6 on 2025-11-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_certification_externalexperience_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_code', models.CharField(max_length=10, unique=True)),
                ('grade_name', models.CharField(max_length=100)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade_code'],
            },
        ),
        migrations.CreateModel(
            name='InternalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('presentation_reason', models.CharField(blank=True, choices=[('Promotion', 'Promotion'), ('Transfer', 'Transfer'), ('Grading Review', 'Grading Review')], max_length=50, null=True)),
                ('presentation_document', models.FileField(blank=True, null=True, upload_to='internal_experience_presentations/%Y/%m/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('results_document', models.FileField(blank=True, null=True, upload_to='internal_experience_results/%Y/%m/')),
                ('final_comments', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_experiences', to='masters.employee')),
                ('grading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.grading')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
    ]
