# Generated by Django 5.2.6 on 2025-11-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_grading_internalexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='join_date',
        ),
    ]
